permalink: pl/:year:month:day:title:output_ext
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
exclude: [".editorconfig", ".gitignore", "scripts", "model", "tagtemplate"]
markdown: kramdown
highlighter: rouge
